### PR TITLE
UPDATE

### PR DESCRIPTION
**Pull request by yocodigo**
Added the selection sort challenge into the sort katas file.

### CODE REVIEW

**Comment by Trewaters** [comment]
Day 3! Excellent

**Comment by Trewaters** [comment]
Great job on Day #5!

I want to clarify with you about the difference between the "...kata" and "...guide" files. First off my examples are not great. I need to update them. The intent was that the kata have no code and the guide have the corresponding code, labeled clearly, to complete the "kata" if the sifu is having trouble. 

I think your files have it reversed. I am not sure so if I have it mistaken it is no problem to let me know.

Keep up the hard work. I am looking forward to trying your katas when I have a break in my studying!

**Comment by Trewaters** [comment]
Day #6 looking good.

I appreciate you swapping that content. 

I need to update some of my files too. You are not alone. This is also a good way to keep our dojo standards. Chat with you later today. Happy friday.

**Comment by Trewaters** [comment]
Keep grinding! 1/19/2019 was day 8 of 30 towards a white belt.

**Comment by Trewaters** [comment]
Day 9 of 30. The insertion sort is coming together. Looking forward to practicing this. I enjoy algorithms.

**Comment by Trewaters** [comment]
Day 10! I like the quick sort.

**Comment by Trewaters** [comment]
Day 14! How are you feeling?

**Comment by yocodigo** [comment]
I feel good. Been working lately so I haven't spend as much time on this as I'd like but I definitely feel more knowledgeable about algorithms and how they're structures and efficiencies.

**Comment by Trewaters** [comment]
Time is tough to manage. I have to do my coding 1st thing in the morning or else the day puts obstacles in my way. It took a while for me to realize that.

Congrats on making it half way to 30 days!!!

**Comment by Trewaters** [comment]
Yesterday was Day 5. Excellent job getting back on track.

**Comment by Trewaters** [comment]
On Day 8 of the challenge!

**Comment by Trewaters** [comment]
Day 9! 
TGIF

**Comment by Trewaters** [comment]
Day 10!

**Comment by Trewaters** [comment]
Keep at it. It took me forever before I was able to do 30 days "in a row". Sounds easy but considering there are not breaks it is a marathon. Now that I am working on the 301 days of code, with no breaks. I decided to not allow myself breaks just because I am crazy. I have to really put effort in to make sure I am coding each day.

I would suggest moving your work and commits to the morning or earlier in the day. See if this helps you get past the midway mark.

If we put both your efforts together it would add up to 30 days! So close man. Keep up the hard work!

**Comment by yocodigo** [comment]
> Keep at it. It took me forever before I was able to do 30 days "in a row". Sounds easy but considering there are not breaks it is a marathon. Now that I am working on the 301 days of code, with no breaks. I decided to not allow myself breaks just because I am crazy. I have to really put effort in to make sure I am coding each day.
> 
> I would suggest moving your work and commits to the morning or earlier in the day. See if this helps you get past the midway mark.
> 
> If we put both your efforts together it would add up to 30 days! So close man. Keep up the hard work!

I'll definitely start committing earlier. Thanks for the support and encouragement Tre'!

**Comment by Trewaters** [comment]
Day 3!

Look forward to catching up this week. I will drop you a line on slack.

**Pull request merged**
